### ISSUE TITLE
Gulp task for CSS minify not working

### ISSUE THREAD

**Issue by peter-doherty** [BlackrockDigital/startbootstrap-resume#24]
Hi,

When I run gulp, I get an error:

PS C:\Users\peter\Documents\GitHub\mysite> gulp
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\peter\Documents\GitHub\mysite\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\peter\Documents\GitHub\mysite\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\peter\Documents\GitHub\mysite\gulpfile.js:88:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

When I inspect the gulpfile error shown at line 88:6 it flags the minify CSS task. I'm using gulp versions:
CLI version 2.0.1
Local version 4.0.0

Has anyone observed this issue?
Thanks

**Comment by peter-doherty** [comment]
I found a solution as I'm using v4 of Gulp. Basically, you add series and parallel into your gulp.task. [Explained here](https://medium.com/m/signin?redirect=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Fp%2F271ae63530c0%3Ftoken%3Dnzvg2wBVHkvCXEaK%26source%3Dpost_share_widget-----271ae63530c0---------------------clap_sidebar%26redirectUrl%3Dhttps%253A%252F%252Fmedium.com%252Fcodeburst&referrer=https%3A%2F%2Fcodeburst.io%2Fswitching-to-gulp-4-0-271ae63530c0&originalAction=multivote)

e.g. gulp.task('css:minify', gulp.series(gulp.parallel('css:compile')), function() {

**Comment by davidtmiller** [comment]
This should be addressed in the most recent fix to the README. Thanks!
